name = "leaflet"
author = "sylvrs"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98a168cb87f6cd7843815c5cebbda32c5047025f9f3a4ad2d36b068fdfa8ad6d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
