name = "leaflet"
author = "sylvrs"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ccd6febfe41b0583759286245745112df7989285d47c575d7aa2834e779529"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
