name = "leaflet"
author = "sylvrs"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af524f2dacd06bd2d299b1b2d0d974bf1beb2025eeb4e6b1aa091c8bc8a18834"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
